song_1_lyrics = [
  "Believer",
  "First things first",
  "I'ma say all the words inside my head",
  "I'm fired up and tired of the way that things have been, oh-ooh",
  "The way that things have been, oh-ooh",
  "Second thing second",
  "Don't you tell me what you think that I could be",
  "I'm the one at the sail, I'm the master of my sea, oh-ooh",
  "The master of my sea, oh-ooh",
  "I was broken from a young age",
  "Taking my sulking to the masses",
  "Writing my poems for the few",
  "That look at me, took to me, shook to me, feeling me",
  "Singing from heartache from the pain",
  "Taking my message from the veins",
  "Speaking my lesson from the brain",
  "Seeing the beauty through the...",
  "Pain!",
  "You made me a, you made me a believer, believer",
  "Pain!",
  "You break me down and build me up, believer, believer",
  "Pain!",
  "Oh, let the bullets fly, oh, let them rain",
  "My life, my love, my drive, it came from...",
  "Pain!",
  "You made me a, you made me a believer, believer",
  "First things first",
  "Can you imagine what's about to happen?",
  "It's Weezy the Dragon, I link with the Dragons",
  "And we gon' get ratchet, no need for imaginin'",
  "This is what's happenin'",
  "Second thing second, I reckon immaculate",
  "Sound about accurate",
  "I know that strength, it don't come, don't come without strategy",
  "I know the sweet, it don't come without cavities",
  "I know the passages come with some traffic",
  "I start with from the basement, end up in the attic",
  "And third thing third",
  "Whoever call me out, they simply can't count",
  "Let's get mathematic, I'm up in this, huh",
  "Is you a believer?",
  "I get a unicorn out of a zebra",
  "I wear my uniform like a tuxedo",
  "This dragon don't hold his breath, don't need no breather",
  "Love you Ms. Cita, the son of a leader",
  "I know the bloomin' don't come without rain",
  "I know the losin' don't come without shame",
  "I know the beauty don't come without hurt",
  "Hol' up, hol' up, last thing last",
  "I know that Tunechi don't come without Wayne",
  "I know that losin' don't come without game",
  "I know that glory don't come without...",
  "Don't come without...",
  "Pain!",
  "You made me a, you made me a believer, believer",
  "Pain!",
  "You break me down and build me up, believer, believer",
  "Pain",
  "Oh, let the bullets fly, oh, let them rain",
  "My life, my love, my drive, it came from...",
  "Pain!",
  "You made me a, you made me a believer, believer",
  "Last things last",
  "By the grace of fire and flames",
  "You're the face of the future, the blood in my veins, oh-ooh",
  "The blood in my veins, oh-ooh",
  "But they never did, ever lived, ebbing and flowing",
  "Inhibited, limited 'til it broke open and rained down",
  "It rained down, like...",
  "Pain!",
  "You made me a, you made me a believer, believer",
  "Pain!",
  "You break me down and build me up, believer, believer",
  "Pain",
  "Oh, let the bullets fly, oh, let them rain",
  "My life, my love, my drive, it came from...",
  "Pain!",
  "You made me a, you made me a believer, believer",
],

song_2_lyrics = [
    "Arcade",
    "Ooh-ooh-ooh, ooh-ooh, ooh-ooh",
    "Ooh-ooh-ooh, ooh-ooh, ooh-ooh",
    "A broken heart is all that's left",
    "I'm still fixing all the cracks",
    "Lost a couple of pieces when",
    "I carried it, carried it, carried it home",
    "I'm afraid of all I am",
    "My mind feels like a foreign land",
    "Silence ringing inside my head",
    "Please, carry me, carry me, carry me home",
    "I've spent all of the love I saved",
    "We were always a losing game",
    "Small-town boy in a big arcade",
    "I got addicted to a losing game",
    "Ooh, ooh",
    "All I know, all I know",
    "Loving you is a losing game",
    "How many pennies in the slot?",
    "Giving us up didn't take a lot",
    "I saw the end 'fore it begun",
    "Still I carried, I carried, I carry on",
    "Ooh, ooh",
    "All I know, all I know",
    "Loving you is a losing game",
    "Ooh, ooh",
    "All I know, all I know",
    "Loving you is a losing game",
    "I don't need your games, game over",
    "Get me off this roller-coaster",
    "Ooh, ooh",
    "All I know, all I know",
    "Loving you is a losing game",
    "Ooh, ooh",
    "All I know, all I know",
    "Loving you is a losing game",
    "Ooh-ooh-ooh, ooh-ooh, ooh-ooh",
    "Ooh-ooh-ooh, ooh-ooh, ooh-ooh",
],

song_3_lyrics = [
    "Lovely",
    "Thought I found a way",
    "Thought I found a way, yeah (found)",
    "But you never go away (never go away)",
    "So I guess I gotta stay now",
    "[Pre-Chorus: Billie Eilish & Khalid]",
    "Oh, I hope some day I'll make it out of here",
    "Even if it takes all night or a hundred years",
    "Need a place to hide, but I can't find one near",
    "Wanna feel alive, outside I can fight my fear",
    "[Chorus: Billie Eilish,Billie Eilish & Khalid]",
    "Isn't it lovely, all alone",
    "Heart made of glass, my mind of stone",
    "Tear me to pieces, skin and bone",
    "Hello, welcome home",
    "[Verse 2: Khalid,Khalid & Billie Eilish]",
    "Walkin' out of town",
    "Lookin' for a better place (lookin' for a better place)",
    "Something's on my mind",
    "Always in my headspace",
    "[Pre-Chorus: Billie Eilish & Khalid]",
    "Oh, I hope some day I'll make it out of here",
    "Even if it takes all night or a hundred years",
    "Need a place to hide, but I can't find one near",
    "Wanna feel alive, outside I can fight my fear",
    "[Chorus: Billie Eilish,Billie Eilish & Khalid]",
    "Isn't it lovely, all alone",
    "Heart made of glass, my mind of stone",
    "Tear me to pieces, skin and bone",
    "Hello, welcome home",
    "[Outro: Khalid,Billie Eilish,Khalid & Billie Eilish]",
    "Woah, yeah",
    "Yeah, ah",
    "Woah, woah",
    "Hello, welcome home",
],

song_4_lyrics = [
    "Happier",
    "Lately, I've been, I've been thinking",
    "I want you to be happier, I want you to be happier",
    "[Verse 1]",
    "When the morning comes",
    "When we see what we've become",
    "In the cold light of day, we're a flame in the wind",
    "Not the fire that we've begun",
    "Every argument, every word we can't take back",
    "'Cause with all that has happened",
    "I think that we both know the way that this story ends",
    "[Chorus]",
    "Then only for a minute",
    "I want to change my mind",
    "'Cause this just don't feel right to me",
    "I wanna raise your spirits",
    "I want to see you smile but",
    "Know that means I'll have to leave",
    "[Post-Chorus]",
    "Know that means I'll have to leave",
    "Lately, I've been, I've been thinking",
    "I want you to be happier, I want you to be happier",
    "You might also like",
    "A&W",
    "Lana Del Rey",
    "Castles Crumbling (Taylor’s Version) [From The Vault]",
    "Taylor Swift",
    "When Emma Falls in Love (Taylor’s Version) [From The Vault]",
    "Taylor Swift",
    "[Verse 2]",
    "When the evening falls",
    "And I'm left there with my thoughts",
    "And the image of you being with someone else",
    "Well, it's eating me up inside",
    "But we ran our course, we pretended we're okay",
    "Now if we jump together, at least we can swim",
    "Far away from the wreck we made",
    "[Chorus]",
    "Then only for a minute",
    "I want to change my mind",
    "'Cause this just don't feel right to me",
    "I wanna raise your spirits",
    "I want to see you smile but",
    "Know that means I'll have to leave",
    "[Post-Chorus]",
    "Know that means I'll have to leave",
    "Lately, I've been, I've been thinking",
    "I want you to be happier, I want you to be happier",
    "[Bridge]",
    "So I'll go, I'll go",
    "I will go, go, go",
    "So I'll go, I'll go",
    "I will go, go, go",
    "[Pre-Chorus]",
    "Lately, I've been, I've been thinking",
    "I want you to be happier, I want you to be happier",
    "Even though I might not like this",
    "I think that you'll be happier, I want you to be happier",
    "[Chorus]",
    "Then only for a minute (Only for a minute)",
    "I want to change my mind",
    "'Cause this just don't feel right to me (Right to me)",
    "I wanna raise your spirits (Wanna raise your spirits)",
    "I want to see you smile but",
    "Know that means I'll have to leave",
    "[Post-Chorus]",
    "Know that means I'll have to leave",
    "Lately, I've been, I've been thinking",
    "I want you to be happier, I want you to be happier",
    "[Outro]",
    "So I'll go, I'll go",
    "I will go, go, go",
],

song_5_lyrics = [
    "Thunder",
    "Just a young gun with a quick fuse",
    "I was uptight, wanna let loose",
    "I was dreaming of bigger things",
    "And wanna leave my old life behind",
    "Not a yessir, not a follower",
    "Fit the box, fit the mold",
    "Have a seat in the foyer, take a number",
    "I was lightning before the thunder",
    "[Chorus]",
    "Thunder, feel the thunder",
    "Lightning then the thunder",
    "Thunder, feel the thunder",
    "Lightning then the thunder",
    "Thunder, thunder",
    "Thunder",
    "[Verse 2]",
    "Kids were laughing in my classes",
    "While I was scheming for the masses",
    "Who do you think you are?",
    "Dreaming 'bout being a big star",
    "They say you're basic, they say you're easy",
    "You're always riding in the backseat",
    "Now I'm smiling from the stage",
    "While you were clapping in the nose bleeds",
    "[Chorus]",
    "Thunder, feel the thunder",
    "Lightning then the thunder",
    "Thunder, feel the thunder",
    "Lightning then the thunder",
    "Thunder",
    "[Bridge]",
    "Thunder, feel the thunder",
    "Lightning then the thunder, thunder",
    "[Chorus]",
    "Thunder, feel the thunder",
    "Lightning then the thunder, thunder",
    "Thunder, feel the thunder",
    "Lightning then the thunder, thunder",
    "Thunder, feel the thunder",
    "Lightning then the thunder, thunder",
    "Thunder, feel the thunder",
    "Lightning then the thunder, thunder",
];
